version: '3.8'
networks:
  pulsar:
    driver: bridge

services:
  # Pulsar standalone - Incluye ZooKeeper, BookKeeper y Broker en un solo contenedor
  pulsar:
    image: apachepulsar/pulsar:latest
    profiles: ["pulsar"]
    container_name: pulsar
    hostname: pulsar
    restart: on-failure
    networks:
      - pulsar
    user: "0:0"  # Ejecutar como root para evitar problemas de permisos
    environment:
      - PULSAR_MEM=-Xms512m -Xmx512m -XX:MaxDirectMemorySize=256m
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 512m
    volumes:
      - ./data/pulsar:/pulsar/data
    ports:
      - "6650:6650"  # Pulsar broker port
      - "8080:8080"  # Pulsar admin port
    command: |
      bash -c "
        chown -R pulsar:pulsar /pulsar/data || true
        exec bin/pulsar standalone
      "
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/admin/v2/brokers/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 30
      start_period: 60s
